# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FireStream' do
  use_frameworks!
  # Pods for FireStream
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Firebase/Database'
end
